# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a52ceb2f2d0d7abb6c8a78a5295a2225516c9dabaec4af3b54b95ae47c36a80e24ba21759c90d019b4452cd93236a4de83a42d803b1d17fe104108ea8130801

test:
  secret_key_base: b0a934c9e4ae05e17ebca3c83e07b85745a7e90011582a177d27449813d06f084485238e5a7ac0dc5bc515cdf91005a9799844c4f89c0b8ef7a5349e3269dc3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
